# Generated by Django 5.0.3 on 2024-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_remove_groceryitem_quantity_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerytransaction',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
