# Generated by Django 5.0.3 on 2024-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_alter_grocerytransaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerytransaction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
