# Generated by Django 5.0.3 on 2024-12-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_grocerytransaction_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='price_per_unit',
            new_name='price_per_kg',
        ),
    ]
